import type { Pin } from '@/types';

// Mock data for demonstration
export const mockPins: Pin[] = [
  {
    id: '1',
    imageUrl: 'https://picsum.photos/400/600?random=1',
    title: 'Beautiful Landscape',
    author: 'Inoe lifestyle',
    width: 400,
    height: 600,
  },
  {
    id: '2',
    imageUrl: 'https://picsum.photos/400/500?random=2',
    title: 'Cute Cat',
    author: 'zangyeon',
    width: 400,
    height: 500,
  },
  {
    id: '3',
    imageUrl: 'https://picsum.photos/400/700?random=3',
    title: 'Anime Character',
    author: '',
    width: 400,
    height: 700,
  },
  {
    id: '4',
    imageUrl: 'https://picsum.photos/400/550?random=4',
    title: 'Gaming Setup',
    author: '',
    width: 400,
    height: 550,
  },
  {
    id: '5',
    imageUrl: 'https://picsum.photos/400/650?random=5',
    title: 'Fashion Style',
    author: '',
    width: 400,
    height: 650,
  },
  {
    id: '6',
    imageUrl: 'https://picsum.photos/400/450?random=6',
    title: 'Nature Photography',
    author: '',
    width: 400,
    height: 450,
  },
  {
    id: '7',
    imageUrl: 'https://picsum.photos/400/600?random=7',
    title: 'Architecture',
    author: '',
    width: 400,
    height: 600,
  },
  {
    id: '8',
    imageUrl: 'https://picsum.photos/400/520?random=8',
    title: 'Food Photography',
    author: '',
    width: 400,
    height: 520,
  },
  {
    id: '9',
    imageUrl: 'https://picsum.photos/400/680?random=9',
    title: 'Travel Destination',
    author: '',
    width: 400,
    height: 680,
  },
  {
    id: '10',
    imageUrl: 'https://picsum.photos/400/580?random=10',
    title: 'Art & Design',
    author: '',
    width: 400,
    height: 580,
  },
  {
    id: '11',
    imageUrl: 'https://picsum.photos/400/620?random=11',
    title: 'Minimalist Interior',
    author: '',
    width: 400,
    height: 620,
  },
  {
    id: '12',
    imageUrl: 'https://picsum.photos/400/540?random=12',
    title: 'Street Photography',
    author: '',
    width: 400,
    height: 540,
  },
  {
    id: '13',
    imageUrl: 'https://picsum.photos/400/660?random=13',
    title: 'Abstract Art',
    author: '',
    width: 400,
    height: 660,
  },
  {
    id: '14',
    imageUrl: 'https://picsum.photos/400/480?random=14',
    title: 'Wildlife',
    author: '',
    width: 400,
    height: 480,
  },
  {
    id: '15',
    imageUrl: 'https://picsum.photos/400/640?random=15',
    title: 'Fashion Editorial',
    author: '',
    width: 400,
    height: 640,
  },
  {
    id: '16',
    imageUrl: 'https://picsum.photos/400/560?random=16',
    title: 'Vintage Style',
    author: '',
    width: 400,
    height: 560,
  },
  {
    id: '17',
    imageUrl: 'https://picsum.photos/400/590?random=17',
    title: 'Modern Architecture',
    author: 'Design Studio',
    width: 400,
    height: 590,
  },
  {
    id: '18',
    imageUrl: 'https://picsum.photos/400/510?random=18',
    title: 'Coffee & Lifestyle',
    author: '',
    width: 400,
    height: 510,
  },
  {
    id: '19',
    imageUrl: 'https://picsum.photos/400/670?random=19',
    title: 'Mountain View',
    author: 'Nature Lover',
    width: 400,
    height: 670,
  },
  {
    id: '20',
    imageUrl: 'https://picsum.photos/400/530?random=20',
    title: 'Urban Photography',
    author: '',
    width: 400,
    height: 530,
  },
  {
    id: '21',
    imageUrl: 'https://picsum.photos/400/610?random=21',
    title: 'Sunset Beach',
    author: 'Travel Diary',
    width: 400,
    height: 610,
  },
  {
    id: '22',
    imageUrl: 'https://picsum.photos/400/490?random=22',
    title: 'Minimalist Design',
    author: '',
    width: 400,
    height: 490,
  },
  {
    id: '23',
    imageUrl: 'https://picsum.photos/400/630?random=23',
    title: 'Botanical Garden',
    author: 'Green Life',
    width: 400,
    height: 630,
  },
  {
    id: '24',
    imageUrl: 'https://picsum.photos/400/570?random=24',
    title: 'City Lights',
    author: '',
    width: 400,
    height: 570,
  },
  {
    id: '25',
    imageUrl: 'https://picsum.photos/400/690?random=25',
    title: 'Ocean Waves',
    author: 'Sea Explorer',
    width: 400,
    height: 690,
  },
  {
    id: '26',
    imageUrl: 'https://picsum.photos/400/500?random=26',
    title: 'Cozy Home',
    author: '',
    width: 400,
    height: 500,
  },
  {
    id: '27',
    imageUrl: 'https://picsum.photos/400/650?random=27',
    title: 'Forest Path',
    author: 'Wanderlust',
    width: 400,
    height: 650,
  },
  {
    id: '28',
    imageUrl: 'https://picsum.photos/400/520?random=28',
    title: 'Dessert Inspiration',
    author: '',
    width: 400,
    height: 520,
  },
  {
    id: '29',
    imageUrl: 'https://picsum.photos/400/600?random=29',
    title: 'Artistic Portrait',
    author: 'Photo Studio',
    width: 400,
    height: 600,
  },
  {
    id: '30',
    imageUrl: 'https://picsum.photos/400/550?random=30',
    title: 'Workspace Goals',
    author: '',
    width: 400,
    height: 550,
  },
  {
    id: '31',
    imageUrl: 'https://picsum.photos/400/640?random=31',
    title: 'Tropical Paradise',
    author: 'Island Vibes',
    width: 400,
    height: 640,
  },
  {
    id: '32',
    imageUrl: 'https://picsum.photos/400/480?random=32',
    title: 'Vintage Camera',
    author: '',
    width: 400,
    height: 480,
  },
  {
    id: '33',
    imageUrl: 'https://picsum.photos/400/620?random=33',
    title: 'Autumn Colors',
    author: 'Season Shots',
    width: 400,
    height: 620,
  },
  {
    id: '34',
    imageUrl: 'https://picsum.photos/400/540?random=34',
    title: 'Street Art',
    author: '',
    width: 400,
    height: 540,
  },
  {
    id: '35',
    imageUrl: 'https://picsum.photos/400/680?random=35',
    title: 'Luxury Interior',
    author: 'Home Decor',
    width: 400,
    height: 680,
  },
  {
    id: '36',
    imageUrl: 'https://picsum.photos/400/510?random=36',
    title: 'Healthy Food',
    author: '',
    width: 400,
    height: 510,
  },
];
