import type { Pin } from '@/types';

// Mock data for demonstration
export const mockPins: Pin[] = [
  {
    id: '1',
    imageUrl: 'https://picsum.photos/400/600?random=1',
    title: 'Beautiful Landscape',
    author: 'Inoe lifestyle',
    width: 400,
    height: 600,
  },
  {
    id: '2',
    imageUrl: 'https://picsum.photos/400/500?random=2',
    title: 'Cute Cat',
    author: 'zangyeon',
    width: 400,
    height: 500,
  },
  {
    id: '3',
    imageUrl: 'https://picsum.photos/400/700?random=3',
    title: 'Anime Character',
    author: '',
    width: 400,
    height: 700,
  },
  {
    id: '4',
    imageUrl: 'https://picsum.photos/400/550?random=4',
    title: 'Gaming Setup',
    author: '',
    width: 400,
    height: 550,
  },
  {
    id: '5',
    imageUrl: 'https://picsum.photos/400/650?random=5',
    title: 'Fashion Style',
    author: '',
    width: 400,
    height: 650,
  },
  {
    id: '6',
    imageUrl: 'https://picsum.photos/400/450?random=6',
    title: 'Nature Photography',
    author: '',
    width: 400,
    height: 450,
  },
  {
    id: '7',
    imageUrl: 'https://picsum.photos/400/600?random=7',
    title: 'Architecture',
    author: '',
    width: 400,
    height: 600,
  },
  {
    id: '8',
    imageUrl: 'https://picsum.photos/400/520?random=8',
    title: 'Food Photography',
    author: '',
    width: 400,
    height: 520,
  },
  {
    id: '9',
    imageUrl: 'https://picsum.photos/400/680?random=9',
    title: 'Travel Destination',
    author: '',
    width: 400,
    height: 680,
  },
  {
    id: '10',
    imageUrl: 'https://picsum.photos/400/580?random=10',
    title: 'Art & Design',
    author: '',
    width: 400,
    height: 580,
  },
  {
    id: '11',
    imageUrl: 'https://picsum.photos/400/620?random=11',
    title: 'Minimalist Interior',
    author: '',
    width: 400,
    height: 620,
  },
  {
    id: '12',
    imageUrl: 'https://picsum.photos/400/540?random=12',
    title: 'Street Photography',
    author: '',
    width: 400,
    height: 540,
  },
  {
    id: '13',
    imageUrl: 'https://picsum.photos/400/660?random=13',
    title: 'Abstract Art',
    author: '',
    width: 400,
    height: 660,
  },
  {
    id: '14',
    imageUrl: 'https://picsum.photos/400/480?random=14',
    title: 'Wildlife',
    author: '',
    width: 400,
    height: 480,
  },
  {
    id: '15',
    imageUrl: 'https://picsum.photos/400/640?random=15',
    title: 'Fashion Editorial',
    author: '',
    width: 400,
    height: 640,
  },
  {
    id: '16',
    imageUrl: 'https://picsum.photos/400/560?random=16',
    title: 'Vintage Style',
    author: '',
    width: 400,
    height: 560,
  },
];
